### ISSUE TITLE
<Model: Object> is not JSON serializable

### ISSUE THREAD

**Issue by martibosch** [diefenbach/django-reviews#2]
I have a very simple model:

from django.db import models

class Place(models.Model):
    name = models.CharField(max_length=100)

```
def __unicode__(self):
    return self.name
```

However, after adding a review (with REVIEWS_SHOW_PREVIEW = False and REVIEWS_IS_MODERATED = False), I get this TypeError:

TypeError at /reviews/add/<content_type_id>/<content_id>
<Place: <name>> is not JSON serializable

Nevertheless, it actually does save the review in the DB. When is it needed to serialize the objects? Does it have to do with the forms? Anyway what do I have to do to make it JSON serializable?

Thanks!

**Comment by diefenbach** [comment]
Please post the whole traceback.

**Comment by martibosch** [comment]
Environment:

Request Method: POST
Request URL: http://ec2-54-77-118-44.eu-west-1.compute.amazonaws.com:5000/reviews/add/11/1

Django Version: 1.6.5
Python Version: 2.7.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'south',
 'places',
 'reviews')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/home/ubuntu/webapps/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                 response = middleware_method(request, response)
   File "/home/ubuntu/webapps/local/lib/python2.7/site-packages/django/contrib/sessions/middleware.py" in process_response
2.                     request.session.save()
   File "/home/ubuntu/webapps/local/lib/python2.7/site-packages/django/contrib/sessions/backends/db.py" in save
3.             session_data=self.encode(self._get_session(no_load=must_create)),
   File "/home/ubuntu/webapps/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py" in encode
4.         serialized = self.serializer().dumps(session_dict)
   File "/home/ubuntu/webapps/local/lib/python2.7/site-packages/django/core/signing.py" in dumps
5.         return json.dumps(obj, separators=(',', ':')).encode('latin-1')
   File "/usr/lib/python2.7/json/**init**.py" in dumps
6.         sort_keys=sort_keys, **kw).encode(obj)
   File "/usr/lib/python2.7/json/encoder.py" in encode
7.         chunks = self.iterencode(o, _one_shot=True)
   File "/usr/lib/python2.7/json/encoder.py" in iterencode
8.         return _iterencode(o, 0)
   File "/usr/lib/python2.7/json/encoder.py" in default
9.         raise TypeError(repr(o) + " is not JSON serializable")

Exception Type: TypeError at /reviews/add/11/1
Exception Value: <Place: Teteria India> is not JSON serializable

**Comment by martibosch** [comment]
I think the problem is that from Django 1.6, sessions use JSON serialization by default, (see https://docs.djangoproject.com/en/1.6/topics/http/sessions/#session-serialization).

So for the views (https://github.com/diefenbach/django-reviews/blob/master/reviews/views.py), when using a session request from the 'save' to the 'thank_you' method, the 'object' instance sent should be serialized.

**Comment by chhantyal** [comment]
@martibosch You are right. You can also add 

`SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer`

in your settings file and old behaviour will work fine.

**Comment by diefenbach** [comment]
Fixed!
